### PR TITLE
PLATFORM-1122 remove requirements for hard coded credentials

### PR DESCRIPTION
**Pull request by pguinard-public-com**

### CODE REVIEW

**Comment by stigok** [comment]
This looks pretty good! Please reopen if you would like feedback and looking to get this merged :+1:

**Comment by pguinard-public-com** [comment]
> This looks pretty good! Please reopen if you would like feedback and looking to get this merged 👍

We are not quite ready yet and are developing internally still.

**Comment by pguinard-public-com** [comment]
We've been migrating to this but have not written the go tests yet. Were still looking at reopening this and upstreaming changes.

**Comment by pguinard-public-com** [comment]
We've cleaned this up and moved it into https://github.com/nrkno/terraform-registry/pull/147 as it's been squashed.

**Pull request closed without merging**
