### PR TITLE
ci: add release-please releaser action

### PR DESCRIPTION
**Pull request by stigok**
https://github.com/google-github-actions/release-please-action

### CODE REVIEW

**Comment by joberget** [comment]
@stigok any doc on this?

**Review by umglurf — DISMISSED** [review]
hvorfor ikke bruke semantic-release?

**Comment by stigok** [comment]
> hvorfor ikke bruke semantic-release?

Fordi den ikke støtter v0 releases https://github.com/semantic-release/semantic-release/issues/1507

**Comment by stigok** [comment]
> @stigok any doc on this?

I have updated the PR description with a link

**Comment by umglurf** [comment]
> > hvorfor ikke bruke semantic-release?
> 
> Fordi den ikke støtter v0 releases [semantic-release/semantic-release#1507](https://github.com/semantic-release/semantic-release/issues/1507)

I think this is good enough for v1 now, better to use the common release system than running something different here

**Comment by stigok** [comment]
> > > hvorfor ikke bruke semantic-release?
> > 
> > 
> > Fordi den ikke støtter v0 releases [semantic-release/semantic-release#1507](https://github.com/semantic-release/semantic-release/issues/1507)
> 
> I think this is good enough for v1 now, better to use the common release system than running something different here

I disagree. We should first sort out any breaking change in the issue list before going v1. We can also change releaser action once (right before) we hit v1. This is also a good chance to see if release-please workflow might work better for this sort of projects, where we don't necessarily want a new release for every new PR coming in.

**Pull request merged**
